permalink: pretty
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
sass:
  style: compressed
include:
  - .well-known
exclude:
  # `vendor/` is excluded because of <https://github.com/jekyll/jekyll/issues/3330>
  - vendor/
  - CNAME
  - Gemfile
  - LICENSE.md
  - README.md

strict_front_matter: true

liquid:
  error_mode: strict
  strict_filters: true
