name: build
on: [push, pull_request]

env:
  global:
    NOKOGIRI_USE_SYSTEM_LIBRARIES=true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Install Ruby
      uses: ruby/setup-ruby@master
      with:
        ruby-version: 3.0.5
    - name: Install dependencies
      run: |
       sudo apt-get update
       sudo apt-get install libcurl4-openssl-dev
       bundle config set --local deployment 'true'
       bundle install --jobs=3 --retry=3
    - name: Run tests
      run: |
       bundle exec jekyll build
       bundle exec htmlproofer '_site/' \
         --allow-hash-href --check-html --http-status-ignore 0,403 \
         --url-ignore '/.*good\+first\+issue.*/,/.*wiki\.minetest\.net.*/,/.*dev\.minetest\.net.*/'
